server:
  port: 8001

spring:
  application:
    name: payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloudbase?characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 10
      min-idle: 10
      max-active: 1000
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

swagger:
  enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hhq.payment.domain
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
