server:
  port: 8001
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://peer1:7001/eureka/, http://peer2:7002/eureka/,http://peer3:7003/eureka/